backend:
    name: github
    branch: master
    repo: boy12371/gatsby-netlify-cms
    base_url: https://api.netlify.com

media_folder: static/img
public_folder: /img

collections:
    - name: article
      label: 文章
      folder: src/pages/article/
      create: true
      slug: "{{year}}{{month}}{{day}}-{{hour}}{{minute}}{{second}}-{{slug}}"
      fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: ArticlePost
          - label: 标题
            name: title
            widget: string
            tagname: h1
            default: 文章标题
          - label: 描述
            name: description
            widget: text
            default: 文章描述
          - label: 时间
            name: date
            widget: datetime
            format: "YYYY-MM-DD HH:mm:ss Z"
          - label: 标签
            name: tags
            widget: list
            default:
                - 标签1
                - 标签2
          - label: 主体
            name: body
            widget: markdown

    - name: pages
      label: 单页
      files:
          - file: src/pages/index.md
            label: 首页
            name: index
            fields:
                - label: Template Key
                  name: templateKey
                  widget: hidden
                  default: IndexPage
                - label: 标题
                  name: title
                  widget: string
                  default: 首页
                - label: 描述
                  name: description
                  widget: text
                  default: 首页描述
                - label: 头部
                  name: isHeader
                  widget: boolean
                  default: true
                - label: 轮播
                  name: isCarousel
                  widget: boolean
                  default: true
                - label: 轮播图集
                  name: carouselItems
                  widget: list
                  fields:
                      - label: 标题
                        name: title
                        widget: string
                      - label: 图片
                        name: image
                        widget: string
                      - label: 路径
                        name: path
                        widget: string
                - label: 推荐
                  name: isFeature
                  widget: boolean
                  default: true
                - label: 推荐图集
                  name: featureItems
                  widget: list
                  fields:
                      - label: 标题
                        name: title
                        widget: string
                      - label: 图片
                        name: image
                        widget: string
                      - label: 路径
                        name: path
                        widget: string
                - label: 底部
                  name: isFooter
                  widget: boolean
                  default: true
          - file: src/pages/jobs/index.md
            label: 招聘英才
            name: jobs
            fields:
                - label: Template Key
                  name: templateKey
                  widget: hidden
                  default: JobsPage
                - label: 标题
                  name: title
                  widget: string
                  default: 招聘英才
                - label: 描述
                  name: description
                  widget: text
                  default: 招聘描述
                - label: 头部
                  name: isHeader
                  widget: boolean
                  default: true
                - label: 主体
                  name: body
                  widget: markdown
                - label: 底部
                  name: isFooter
                  widget: boolean
                  default: true
          - file: src/pages/about/index.md
            label: 关于我们
            name: about
            fields:
                - label: Template Key
                  name: templateKey
                  widget: hidden
                  default: AboutPage
                - label: 标题
                  name: title
                  widget: string
                  default: 关于我们
                - label: 描述
                  name: description
                  widget: text
                  default: 关于描述
                - label: 头部
                  name: isHeader
                  widget: boolean
                  default: true
                - label: 主体
                  name: body
                  widget: markdown
                - label: 底部
                  name: isFooter
                  widget: boolean
                  default: true

    - name: settings
      label: 设置
      files:
          - file: src/pages/settings/header.md
            label: 头部
            name: header
            fields:
                - label: Template Key
                  name: templateKey
                  widget: hidden
                  default: HeaderSettings
                - label: 是否显示网标
                  name: isLogo
                  widget: boolean
                  default: true
                - label: 网标设置
                  name: logoItem
                  widget: object
                  fields:
                      - label: 网标文字
                        name: title
                        widget: string
                      - label: 网标图
                        name: image
                        widget: image
                      - label: 路径
                        name: path
                        widget: string
                - label: 是否显示导航
                  name: isNav
                  widget: boolean
                  default: true
                - label: 导航设置
                  name: navItems
                  widget: list
                  fields:
                      - label: 导航文字
                        name: title
                        widget: string
                      - label: 路径
                        name: path
                        widget: string
          - file: src/pages/settings/footer.md
            label: 底部
            name: footer
            fields:
                - label: Template Key
                  name: templateKey
                  widget: hidden
                  default: FooterSettings
                - label: 主体
                  name: body
                  widget: markdown
          - file: src/pages/settings/carousel.md
            label: 轮播
            name: carousel
            fields:
                - label: Template Key
                  name: templateKey
                  widget: hidden
                  default: CarouselSettings
                - label: 时间
                  name: interval
                  widget: number
                  default: 5000
          - file: src/pages/settings/units.md
            label: 单位
            name: units
            fields:
                - label: Template Key
                  name: templateKey
                  widget: hidden
                  default: UnitsSettings
                - label: 货币
                  name: currency
                  widget: string
                - label: 重量
                  name: weight
                  widget: string
